### ISSUE TITLE
Conventions for dimension

### ISSUE THREAD

**Issue by owoodman** [OSTP/PhysicsArtofModelling#166]
What is the correct convention for talking about dimensions?
i.e. Would it be: "velocity has dimension of length over time", "velocity has the dimension of length over time" or "velocity has dimensions of length over time"?

**Comment by ryanmartinneutrino** [comment]
hmmm, they all sound reasonable. I would probably say that, grammatically, "velocity has the dimension of length over time", but the other versions I think are also used colloquially.
