### ISSUE TITLE
Modified section on transmission and reflection

### ISSUE THREAD

**Issue by owoodman** [OSTP/PhysicsArtofModelling#201]
What are your thoughts on this? I left the part about the fixed/free ends the same and then explained how they are limiting cases of the changing density.  
![screen shot 2018-08-01 at 4 28 06 pm](https://user-images.githubusercontent.com/38730915/43547178-82a644a6-95a8-11e8-9158-665a0a6176fd.png)
![screen shot 2018-08-01 at 4 28 11 pm](https://user-images.githubusercontent.com/38730915/43547179-82b487e6-95a8-11e8-973e-4e77bace35eb.png)

**Comment by ryanmartinneutrino** [comment]
I think that's pretty reasonable, but we should include a derivation of the
value of R, perhaps as an end of chapter problem, which we can refer to?
Ryan.

**Comment by owoodman** [comment]
Ok, I've added the derivation to the end of the chapter.
