### ISSUE TITLE
Draft of cover page

### ISSUE THREAD

**Issue by owoodman** [OSTP/PhysicsArtofModelling#236]
Here is a draft of the cover page. Was hoping to get feedback before I put it into the proper format.
![cover draft](https://user-images.githubusercontent.com/38730915/44365122-d4f9f200-a496-11e8-9348-442f9495cf3c.png)

**Comment by ryanmartinneutrino** [comment]
It's looks great! If possible, it might be worth seeing if you can make North America and Europe look a little more realistic, maybe by moving up the perspective so that we see more of those continents? Is there something that could go in the ocean, or would that be too cluttered?

**Comment by owoodman** [comment]
Ok. I think that it would be too cluttered if I put something in the ocean, but I'll see if I can use a different perspective in order to see more of North America and Europe.

**Comment by owoodman** [comment]
I tried a rough draft of a version where I changed the perspective, but it didn't really work out (see image below). I think that unless an entire continent can be seen, its hard to pick up on the fact that it's a globe.

![screen shot 2018-08-21 at 1 56 37 pm](https://user-images.githubusercontent.com/38730915/44419890-6b3b2000-a54a-11e8-9a89-c3e138c2e180.png)

I considered doing a full world map as you suggested, but that would involve making a lot more figures, which I won't have time to do this week.

**Comment by ryanmartinneutrino** [comment]
Alright! I was just being picky, it already looked great!
One more picky comment on the cover, is the location of the dots between author names, which is uneven in your draft. Should the dot be centred between Emma and Olivia, as it is between Ryan and Emma?

**Comment by owoodman** [comment]
Good point, I'll make sure that it's fixed in the final draft!
