### ISSUE TITLE
Latex Solutions of the problems

### ISSUE THREAD

**Issue by enoxos** [OSTP/PhysicsArtofModelling#341]
Hello,
I teach physics and I was wondering if we still have access tot eh LaTeX problem solutions. If we do, how can we request them?
Thank you for an excellent textbook

**Comment by ryanmartinneutrino** [comment]
Hi,
If you send me an email to my account at Queen's University (Department of Physics) from an email address that is associated with an educational institution, I'm happy to email them back to you!
