### ISSUE TITLE
Should we consolidate key takeaways and important equations

### ISSUE THREAD

**Issue by ryanmartinneutrino** [OSTP/PhysicsArtofModelling#74]
Looking at the summaries for 1D, 2D, Work-Energy, I'm thinking that the key takeaways is probably redundant with the quick summary of the equations. Should we just remove the "key take aways" and just have a nice summary like we have written in those chapters for the Important Equations?

**Comment by owoodman** [comment]
I think it makes sense to consolidate them.  For ND at least, I think there are some important points in the Key Takeaways that aren't covered in the Important Equations, so I would be hesitant to just remove that section. However I do think the sections could be easily combined.

**Comment by ryanmartinneutrino** [comment]
yup, we should make sure to include the information from the takeaways into
the important equations (and probably just rename the important equations
box to "key takeaways" or whatever)

**Comment by owoodman** [comment]
[Art of Modelling Copy.pdf](https://github.com/OSTP/PhysicsArtofModelling/files/2081264/Art.of.Modelling.Copy.pdf)

Here's an example of what it could look like if we consolidated the key takeaways/equations and then had a small equations box.

**Comment by ryanmartinneutrino** [comment]
I think that looks great!
Ryan.
