### ISSUE TITLE
Cover, preface, credits

### ISSUE THREAD

**Issue by ryanmartinneutrino** [OSTP/PhysicsArtofModelling#76]
We haven't worked on any of these yet, but we need to make sure that we have:

- A cover for the textbook, which means settling on a final title.
- A preface, outlining the philosophy for the text, how to use it, and referring to the question library.
- A section with credits (maybe at the beginning, just before the prefaces?)
- A CC-BY-SA license

**Comment by owoodman** [comment]
I thought of a couple other variations on the title:
"Introductory Physics: Building Models to Describe Our World"
"Introductory Physics: Modelling Our World" or "Modelling the Physical World"

We could also potentially do a title that eludes to the flipped classroom approach/engaged learning aspect of the book, or maybe the fact that its a calculus-based approach.
